DjangoBBSForum/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.conf.urls import include
from DjangoBBSForum import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bbs/', include("bbs.urls")),
    path('register/', views.register, name="register"),
    path('login/', views.acc_login, name="login"),
    path('logout/', views.acc_logout, name="logout"),
    # 获取验证码
    path('get_validcode_img/', views.get_valid_code_img, name="get_validcode_img"),

    # 所有的都匹配不到走这个
    re_path(r'.*', views.not_found),
]

bbs/urls.py
from django.urls import path
from bbs import views

urlpatterns = [
    path('', views.index, name="bbs"),
    path('category/<int:category_id>/', views.category, name='category'),
    path('article/<int:article_id>/', views.article_detail, name='article_detail'),
    path('comment/', views.comment, name='post_comment'),
    path('comment_list/<int:article_id>/', views.get_comments, name='get_comments'),
    path('new_article/', views.new_article, name='new_article'),
    path('latest_article_count/', views.get_latest_article_count, name='get_latest_article_count'),
]

bbs/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
import datetime
from django.contrib.auth.models import User, AbstractUser


# Create your models here.


class Article(models.Model):
    """
    帖子表
    """
    title = models.CharField(max_length=255)
    # 描述
    brief = models.CharField(null=True, blank=True, max_length=255)
    # on_delete=models.CASCADE：表示级联删除
    category = models.ForeignKey("Category", on_delete=models.CASCADE)
    content = models.TextField(u"文章内容")
    author = models.ForeignKey("UserProfile", on_delete=models.CASCADE)
    # 时间自动生成
    # auto_now_add:保存第一次创建文章时候的时间，后面修改文章时间不改变
    pub_date = models.DateTimeField(blank=True, null=True)
    # auto_now:后面修改文章的话时间改变
    last_modify = models.DateTimeField(auto_now=True)
    priority = models.IntegerField(u"优先级", default=1000)
    # upload_to：将图片文件存储到./uploads目录下，default未没有设置图片时的默认路径（有问题，访问路径总是/static/uploads/default.jpg，访问不到图片）
    # default写什么，数据库中存储路径就是什么
    img = models.ImageField(u"文章标题图片", upload_to="./uploads", default="uploads/default.jpg")

    status_choices = (("draft", u"草稿"), ("published", u"已发布"), ("hidden", u"隐藏"))
    status = models.CharField(choices=status_choices, default="published", max_length=255)

    def clean(self):
        if self.status == "draft" and self.pub_date is not None:
            raise ValidationError("Draft entries may not have a publication date.")
        if self.status == "published" and self.pub_date is None:
            self.pub_date = datetime.date.today()

    def __str__(self):
        return self.title


class Comment(models.Model):
    """
    评论 & 点赞
    """
    article = models.ForeignKey(Article, verbose_name=u"所属文章", on_delete=models.CASCADE)
    parent_comment = models.ForeignKey("self", related_name="my_children", blank=True, null=True, on_delete=models.CASCADE)
    comment_choices = ((1, u'评论'), (2, u'点赞'))
    comment_type = models.IntegerField(choices=comment_choices, default=1)
    user = models.ForeignKey("UserProfile", on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    comment = models.TextField(blank=True, null=True)

    def clean(self):
        """
        评论的话限制内容不为空
        """
        if self.comment_type == 1 and len(self.comment) == 0:
            raise ValidationError("评论内容不能为空")

    def __str__(self):
        return "C:%s" % self.comment


class Category(models.Model):
    """
    板块
    """
    name = models.CharField(max_length=255)
    # blank：针对表单而言，若为True，表示表单填写该字段时可以不填
    # null：针对数据库而言，若为True, 表示数据表中该字段可以为空
    brief = models.CharField(null=True, blank=True, max_length=255)
    # 板块动态展示
    set_as_top_menu = models.BooleanField(default=False)
    position_index = models.SmallIntegerField()
    # 板主
    admins = models.ManyToManyField("UserProfile", blank=True)

    def __str__(self):
        return self.name


class UserProfile(models.Model):
    """
    用户
    """
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    # 昵称
    username = models.CharField(max_length=255)
    signature = models.CharField(max_length=255, blank=True, null=True)
    # 图片尺寸出了问题？？？
    # 去掉height_field=150, width_field=150, 这两个参数，就不会报错了，原因查看https://blog.csdn.net/guothree2003/article/details/96477788
    avatar = models.ImageField(u'头像', upload_to="media", default="media/default.jpg", blank=True, null=True)

    def __str__(self):
        return self.username

templates/base.html
<!DOCTYPE html>
<!-- saved from url=(0049)https://v3.bootcss.com/examples/navbar-fixed-top/ -->
<html lang="zh-CN">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="https://v3.bootcss.com/favicon.ico">

    <title>BBS论坛</title>

    <!-- Bootstrap core CSS -->
    <link href="/statics/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/statics/bootstrap/css/navbar-fixed-top.css" rel="stylesheet">
    {#引入自己写的样式#}
    <link href="/statics/bootstrap/css/custom.css" rel="stylesheet">
</head>

<body>
{% csrf_token %}
<!-- Fixed navbar -->
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/bbs/">BBS论坛</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">

            <ul class="nav navbar-nav">
                {% block tag-menu %}
                {% endblock %}
            </ul>

            <ul class="nav navbar-nav navbar-right">
                {% block login_register %}
                {% endblock %}
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</nav>

<div class="page-container">
    {% block page-container %}
    <!-- Main component for a primary marketing message or call to action -->
    <div class="jumbotron">
        <h2>BASE模板文件</h2>
    </div>
    {% endblock %}
</div> <!-- /container -->
<footer class="footer">
    <div class="footer-font">
        <h1>Solost23出品</h1>
    </div>
</footer>
<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="/statics/bootstrap/js/jquery.min.js.下载"></script>
<script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
<script src="/statics/bootstrap/js/bootstrap.min.js.下载"></script>
{% block bottom-js %}

{% endblock %}


<div class="xl-chrome-ext-bar" id="xl_chrome_ext_{4DB361DE-01F7-4376-B494-639E489D19ED}" style="display: none;">
    <div class="xl-chrome-ext-bar__logo"></div>

    <a id="xl_chrome_ext_download" href="javascript:;" class="xl-chrome-ext-bar__option">下载视频</a>
    <a id="xl_chrome_ext_close" href="javascript:;" class="xl-chrome-ext-bar__close"></a>
</div>
</body>
</html>

templates/login.html
{% extends "base.html" %}

{#登录#}
{% block page-container %}
<form method="post" action="{% url 'login' %}">
    {#csrf_token：防止跨站域请求#}
    {#所有post请求提交数据的时候都要带上这个#}
    {% csrf_token %}
    <div class="form-group">
        <label for="user">用户名:</label>
        <input type="text" id="user" class="form-control" name="user">
    </div>

    <div class="form-group">
        <label for="pwd">密码:</label>
        <input type="password" id="pwd" class="form-control" name="pwd">
    </div>

    <div class="form-group">
        <label for="code">验证码:</label>
        <div class="row">
            <div class="col-md-6">
                <input type="text" id='code' class="form-control" name="code">
            </div>

            <div class="col-md-6">
                <img src="{% url 'get_validcode_img' %}" id="valid_code_img" height="40" width="270">
            </div>
        </div>
    </div>
    <input type="submit" class="btn btn-default login_btn pull-right" value="登陆">
    <a href="{% url 'register' %}" class="btn btn-success">注册</a>
</form>

{% endblock %}

templates/not_found.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>not_found</title>
    <link rel="stylesheet" href="/static/blog/bs/css/bootstrap.css">
    <style>
        body {
            margin: 8% auto 0;
            max-width: 550px;
            min-height: 200px;
            padding: 10px;
            font-family: 'PingFang SC', 'Microsoft YaHei', 'Helvetica Neue', 'Helvetica', 'Arial', sans-serif;
            font-size: 14px;
        }

        p {
            color: #555;
            margin: 10px 10px;
        }

        img {
            border: 0px;
        }

        .d {
            color: #404040;
        }

    </style>
</head>
<body>
<a href=''><img src='/statics/404.jfif' alt='bbs'/></a>
<p class='d'>请确认您输入的网址是否正确，如果问题持续存在，请发邮件至 2805347171&#64;qq.com 与我们联系。</p>
<p><a href='/bbs/'>返回网站首页</a></p>
</body>

</html>

templates/register.html
{% extends "base.html" %}

{#注册#}
{% block page-container %}
<div class="container">
    <div class="row">
        <div class="col-md-6 col-lg-offset-3">

            <form>
                {% csrf_token %}

                {% for field in form %}
                <div class="form-group">
                    <!--                        field.auto_id 拿到input对象的id-->
                    <label for='{{ field.auto_id }}'>{{ field.label }}</label>
                    {{ field }}<span class="error pull-right"></span>
                </div>
                {% endfor %}
                <div class="form-group">
                    <div>
                        <!--                      做成一个label标签，利用for属性，这样点击图片就相当于点击了input-->
                        <label for="avatar">头像
                            <img id='img_avatar' src="/statics/default_avatar.jpg" width="60">
                        </label>
                        <input type="file" id="avatar" style="display:none">
                    </div>
                </div>
                <input type="button" class="btn btn-default reg_btn pull-right" value="注册"><span
                    class="error"></span>
            </form>

        </div>
    </div>
</div>

<script src="/statics/bootstrap/js/jquery.min.js.下载"></script>
<script>
        $('#avatar').change(function () {
            // alert(123)
            // 获取用户选中的文件对象
            var file_obj = $(this)[0].files[0];
            // console.log(file_obj);
            //获取当前文件对象路径
            var reader = new FileReader();
            //获取到的路径存储到reader的result属性中
            reader.readAsDataURL(file_obj);
            // console.log(reader.result);

            //修改img的src属性(保证在读完在去赋值，因为读的比较慢，又是异步执行代码，会导致没读完就赋值)
            reader.onload = function () {
                $('#img_avatar').attr('src', reader.result)
            };
        });

        //绑定提交事件，发送ajax请求
        $('.reg_btn').click(function () {

            var formdata = new FormData();
            formdata.append('user', $('#id_user').val());
            formdata.append('pwd', $('#id_pwd').val());
            formdata.append('re_pwd', $('#id_re_pwd').val());
            formdata.append('email', $('#id_email').val());
            formdata.append('avatar', $('#avatar')[0].files[0]);
            //post请求发送ajax要自己加上csrf_token
            formdata.append('csrfmiddlewaretoken', $("[name='csrfmiddlewaretoken']").val());
            $.ajax({
                    url: '',
                    type: 'post',
                    contentType: false,
                    processData: false,
                    data: formdata,
                    success: function (data) {
                        // console.log(data);
                        if (data.user) {
                            //注册成功
                            // console.log(data);
                            location.href = '/login/'
                        } else {
                            //注册失败
                            //将之前的所有span标签清空
                            $('.error').html('');
                            //移除input框变红效果
                            $('.form-group').removeClass('has-error');
                            // console.log(data.msg);
                            // 循环错误的字段名和其对应的列表,展示此次的错误信息
                            $.each(data.msg, function (field, error_list) {
                                // console.log(field,error_list);
                                if (field == '__all__') {
                                    $('#id_re_pwd').next().html(error_list[0]).parent().addClass('has-error')
                                }
                                $('#id_' + field).next().html(error_list[0]);
                                $('#id_' + field).parent().addClass('has-error')
                            })
                        }
                    }
                }
            )
        })

</script>

{% endblock %}